#!/bin/bash
pkill -9 -f "gz sim"
pkill -9 -f "ruby.*gz"
pkill -9 -f "ros2 launch"
pkill -9 -f "parameter_bridge"
pkill -9 -f "mission_manager_node"
pkill -9 -f "nav2_controller"
pkill -9 -f "nav2_planner"
pkill -9 -f "nav2_smoother"
pkill -9 -f "nav2_behaviors"
pkill -9 -f "nav2_bt_navigator"
pkill -9 -f "nav2_waypoint_follower"
pkill -9 -f "nav2_velocity_smoother"
pkill -9 -f "slam_toolbox"
pkill -9 -f "map_fusion_node"
echo "Cleanup complete."
